# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JC6kV_c9k8PD27p0q7cOLFGvAlM1FpkX
"""

import nbformat

nb = nbformat.read("notebook.ipynb", as_version=4)

# Remove broken widget metadata
if "widgets" in nb.metadata:
    del nb.metadata["widgets"]

nbformat.write(nb, "fixed_notebook.ipynb")

